/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-103910-gc5f3143090-20210929"
#endif /* AVUTIL_FFVERSION_H */
